# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
# from api_keys import g_key
from config import api_key
from config import g_key
print(g_key)

AIzaSyAV4RdXefQGJqTjMiTSHiu7ero7EwsrE_Q

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data_to_load = "../starter_code/output_data_file.csv"
weather_data = pd.read_csv(weather_data_to_load)
weather_data.head(20)

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,mar del plata,20,ES,1604024384,93,43.40,-4.01,55.99,2.24
1,saint-pierre,75,RE,1604024384,56,-21.34,55.48,69.80,14.99
2,nerja,0,ES,1604024384,77,36.76,-3.89,59.00,3.22
3,mataura,100,NZ,1604024384,91,-46.19,168.86,61.00,1.99
4,bathsheba,40,BB,1604024385,88,13.22,-59.52,80.60,23.04
5,albany,100,US,1604024385,90,42.60,-73.97,42.01,10.85
6,baturaja,3,ID,1604024094,61,-4.13,104.17,86.97,2.66
7,rikitea,100,PF,1604024208,73,-23.12,-134.97,75.56,6.73
8,hobart,40,AU,1604024091,67,-42.88,147.33,66.00,17.22
9,tabou,100,CI,1604024385,91,4.42,-7.35,76.98,7.36
10,saint-francois,90,FR,1604024385,93,46.42,3.91,53.60,3.36
11,ushuaia,75,AR,1604024246,70,-54.80,-68.30,44.60,12.75
12,vaini,20,TO,1604024386,65,-21.20,-175.20,77.00,9.17
13,jinxiang,22,CN,1604024386,64,27.43,120.61,67.60,14.88
14,linjiang,0,CN,1604024386,45,41.81,126.91,48.27,1.23
15,belyy yar,100,RU,1604024386,86,55.84,32.94,44.40,5.61
16,cape town,0,CL,1604024386,63,-36.41,-71.90,62.60,5.82
17,clyde river,100,US,1604024386,86,41.30,-82.98,46.99,1.01
18,agogo,71,GH,1604024387,100,6.80,-1.08,69.93,2.80
19,galveston,90,US,1604024387,62,29.37,-94.97,57.20,29.97

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Locations
locations = weather_data[["Lat", "Lng"]]

humidity = weather_data["Humidity"].astype(float)

In [4]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=2)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
# Filter vacation with zero cloudiness
vacation_no_cloud = weather_data[weather_data["Cloudiness"] == 0]
# Filter vacation with max temp above 70 degrees F
vacation_above_70_degrees = vacation_no_cloud[vacation_no_cloud["Max Temp"] > 70]
# Filter vacation with max temp below 80 degrees F
vacation_below_80_degrees = vacation_above_70_degrees[vacation_above_70_degrees["Max Temp"] < 80]
# Filter vacation with wind speed below 10 mph
vacation_slow_wind = vacation_below_80_degrees[vacation_below_80_degrees["Wind Speed"] < 10]
# Filter vacation with humidity below 60 %
perfect_vacation = vacation_slow_wind[vacation_slow_wind["Humidity"] < 60]
# Set Index
indexed_perfect_vacation = perfect_vacation.reset_index()
del indexed_perfect_vacation["index"]
indexed_perfect_vacation.head(10)

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,sao felix do xingu,0,IN,1604024392,57,20.51,76.21,70.25,0.43
1,sao joaquim da barra,0,IN,1604024392,57,20.51,76.21,70.25,0.43
2,sao filipe,0,IN,1604024392,57,20.51,76.21,70.25,0.43
3,airai,0,TL,1604024436,48,-8.93,125.41,77.92,2.62
4,sao miguel do araguaia,0,IN,1604024392,57,20.51,76.21,70.25,0.43
5,bouna,0,CI,1604024457,54,9.27,-3.00,73.72,2.37
6,gonda,0,IN,1604024477,56,27.13,81.93,71.04,4.94
7,ormara,0,PK,1604024477,34,25.21,64.64,75.07,8.34

In [7]:
vaca_locations = indexed_perfect_vacation[["Lat", "Lng"]]

vaca_humidity = indexed_perfect_vacation["Humidity"].astype(float)

# Plot Heatmap
vaca_fig = gmaps.figure()

# Create heat layer
vaca_heat_layer = gmaps.heatmap_layer(vaca_locations, weights=vaca_humidity, 
                                 dissipating=False, max_intensity=50,
                                 point_radius=2.5)

# Add layer
vaca_fig.add_layer(vaca_heat_layer)

# Display figure
vaca_fig

Figure(layout=FigureLayout(height='420px'))

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [9]:
# Hotel variable
hotels = []

# Loop through narrowed down dataframe to get nearest hotel
for city in range(len(indexed_perfect_vacation["City"])):

    lat = indexed_perfect_vacation.loc[city]["Lat"]
    lng = indexed_perfect_vacation.loc[city]["Lng"]

    city_coords = f"{lat},{lng}"

    params = {
        "location": city_coords, 
        "types": "lodging",
        "radius": 5000,
        "key": g_key
    }

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"   

    hotel_request = requests.get(base_url, params=params)
    hotel_response = hotel_request.json()

    try:
        hotels.append(hotel_response["results"][0]["name"])
    except:
        hotels.append("Nearest hotel not found")

# Dataframe with nearest hotel
indexed_perfect_vacation["Nearest Hotel"] = hotels
indexed_perfect_vacation

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Nearest Hotel
0,sao felix do xingu,0,IN,1604024392,57,20.51,76.21,70.25,0.43,Nearest hotel not found
1,sao joaquim da barra,0,IN,1604024392,57,20.51,76.21,70.25,0.43,Nearest hotel not found
2,sao filipe,0,IN,1604024392,57,20.51,76.21,70.25,0.43,Nearest hotel not found
3,airai,0,TL,1604024436,48,-8.93,125.41,77.92,2.62,Nearest hotel not found
4,sao miguel do araguaia,0,IN,1604024392,57,20.51,76.21,70.25,0.43,Nearest hotel not found
5,bouna,0,CI,1604024457,54,9.27,-3.00,73.72,2.37,Nearest hotel not found
6,gonda,0,IN,1604024477,56,27.13,81.93,71.04,4.94,Nearest hotel not found
7,ormara,0,PK,1604024477,34,25.21,64.64,75.07,8.34,Nearest hotel not found

In [ ]:
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Nearest Hotel}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in indexed_perfect_vacation.iterrows()]
locations = indexed_perfect_vacation[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map
fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content= [f"Nearest Hotel: {hotel}" for hotel in hotels])
vaca_fig.add_layer(markers)

# Display Map
vaca_fig